import { z } from 'zod';
import type { RoleKey } from './org';

/**
 * Permission model (docs/02-yeu-cau/dac-ta/01-phan-quyen.md §2.3–§2.6, §3). M1b-04.
 *
 * - A permission key is `object.action` (§2.4). A role maps keys to scopes (§2.3).
 * - ROLE_MATRIX below is GENERATED from the spec §3 by `node tools/authz/gen-permissions.js`;
 *   apps/api/src/authz/matrix.spec.ts fails when it drifts from the spec. Never edit it by hand.
 * - Free-text cells of the spec are read narrowly (tools/authz/matrix-source.js NARROW_CELLS).
 */

/** Scope codes (§2.3). SELF = "Của tôi / Của mình / Tin mình gửi"; ALL = ✅ (not tied to customer data). */
export const SCOPE_CODES = ['TD', 'DV', 'TO', 'NH', 'CT', 'SELF', 'NICK', 'KENH', 'TK', 'LEAD', 'TUYEN', 'YC', 'ALL'] as const;
export type ScopeCode = (typeof SCOPE_CODES)[number];

export const SCOPE_LABELS: Record<ScopeCode, string> = {
  TD: 'TĐ',
  DV: 'DV',
  TO: 'TỔ',
  NH: 'NH',
  CT: 'CT',
  SELF: 'Của tôi',
  NICK: 'NICK',
  KENH: 'KÊNH',
  TK: 'TK',
  LEAD: 'LEAD',
  TUYEN: 'TUYẾN',
  YC: 'YC',
  ALL: '✅',
};

/**
 * How far a cell lets the holder act. full (default) ⊃ propose ⊃ view; request = may only send a request.
 */
export type PermMode = 'full' | 'propose' | 'view' | 'request';

/** One matrix cell. Empty `s` (or missing cell) = ✖. */
export interface PermCell {
  /** Scopes in which the action is allowed. */
  s: ScopeCode[];
  /** `+NK`: every use writes its own audit line. */
  log?: boolean;
  mode?: Exclude<PermMode, 'full'>;
  /** Condition the engine cannot check yet: the cell applies only when the caller asserts it. */
  cond?: string;
  /** "trừ chính mình": never on the actor himself. */
  notSelf?: boolean;
  /** cust.phone_full only: scopes where the full number shows after "Hiện" (logged), not always. */
  reveal?: ScopeCode[];
}

/** channel_access levels (§2.5). */
export const CHANNEL_ACCESS_LEVELS = ['giu_nick', 'gui', 'xem', 'lead'] as const;
export type ChannelAccessLevel = (typeof CHANNEL_ACCESS_LEVELS)[number];

/** Temporary grants (§2.6). */
export const GRANT_TYPES = ['xem_ngoai_pham_vi', 'xem_noi_dung_chat', 'truc_thay', 'ho_tro_ky_thuat', 'uy_quyen_duyet'] as const;
export type GrantType = (typeof GRANT_TYPES)[number];
export const GRANT_STATUSES = ['cho_duyet', 'hieu_luc', 'tu_choi', 'het_han', 'thu_hoi'] as const;
export type GrantStatus = (typeof GRANT_STATUSES)[number];
/** Rights a grant gives on its target (MH-PQ-11 #2). */
export const GRANT_RIGHTS = ['xem', 'ghi_chu', 'tra_loi'] as const;
export type GrantRight = (typeof GRANT_RIGHTS)[number];

/** MCP tool groups (§3.8) by tool name. */
export const MCP_TOOL_GROUPS: Record<string, 'doc' | 'de_xuat' | 'dong_bo' | 'gui_da_duyet'> = {
  search_messages: 'doc',
  get_contact_profile: 'doc',
  get_customer_360: 'doc',
  list_my_tasks: 'doc',
  get_sync_status: 'doc',
  propose_reply_draft: 'de_xuat',
  register_account: 'dong_bo',
  get_checkpoint: 'dong_bo',
  get_field_mapping: 'dong_bo',
  propose_field_mapping: 'dong_bo',
  ingest_contacts: 'dong_bo',
  ingest_groups: 'dong_bo',
  ingest_conversations: 'dong_bo',
  ingest_messages: 'dong_bo',
  create_upload_url: 'dong_bo',
  confirm_upload: 'dong_bo',
  list_pending_suggestions: 'gui_da_duyet',
  mark_sent: 'gui_da_duyet',
};

/** One effective permission of the signed-in user (`GET /api/me/permissions`). */
export interface EffectivePermission {
  scopes: ScopeCode[];
  /** Best mode among the user's roles. */
  mode: PermMode;
  log?: boolean;
  /** Conditions still to meet (see PermCell.cond); empty when an unconditional role grants it. */
  conds?: string[];
  reveal?: ScopeCode[];
}

export interface MePermissions {
  userId: string | null;
  /** Legacy token without a user (AUTHZ_LEGACY_TOKENS=1): every permission, no filtering. */
  legacy: boolean;
  roles: { roleKey: RoleKey; customRoleId?: string; customRoleName?: string; orgUnitId: string; orgUnitName: string; lead: boolean }[];
  /** Only keys the user has (✖ keys are absent: the UI hides those buttons, D8-02). */
  permissions: Partial<Record<PermissionKey, EffectivePermission>>;
  /** Channels (account uid) the user holds as "Người giữ nick". */
  heldChannels: string[];
  /** Holder of an open máy Zalo slot (QR still to scan, or connected): the menu shows "Kết nối kênh" (00 ⁽¹³⁾). */
  zaloSlotHolder?: boolean;
}

/** MH-PQ-11 texts (form A page, form B object). */
export const NO_ACCESS_TEXT = {
  pageTitle: 'Bạn không có quyền truy cập trang này',
  objectTitle: 'Không tìm thấy hoặc bạn không có quyền xem',
  objectDescription: (code: string) => `Mã: ${code}. Nội dung này nằm ngoài phạm vi của bạn.`,
  /** API message of a 403 caused by data scope (same for "missing" and "out of scope", NT8). */
  api: 'Không tìm thấy hoặc bạn không có quyền xem',
  noPermission: (key: string) => `Bạn không có quyền thực hiện thao tác này (${key}).`,
} as const;

/** `0900000201` / `+84900000201` → `0900 *** 201` (MH-PQ-12). Unknown shapes keep only the last 3 digits. */
export function maskPhone(phone: string | null | undefined): string {
  if (!phone) return '';
  let d = String(phone).replace(/\D/g, '');
  if (d.startsWith('84') && d.length === 11) d = `0${d.slice(2)}`;
  if (d.length < 6) return '***';
  return `${d.slice(0, 4)} *** ${d.slice(-3)}`;
}

/** `garage.minhphat@example.vn` → `ga***@example.vn` (MH-PQ-12). */
export function maskEmail(email: string | null | undefined): string {
  if (!email) return '';
  const at = email.indexOf('@');
  if (at < 1) return '***';
  return `${email.slice(0, Math.min(2, at))}***${email.slice(at)}`;
}

/** `POST /api/reveal`: show one masked field in full (logged as `phone.reveal`). */
export const revealInputSchema = z
  .object({
    field: z.enum(['phone']),
    uid: z.string().min(1).max(200),
    userId: z.string().min(1).max(200),
    /** Where the user clicked (MH-PQ-12 #7), for the audit line. */
    where: z.string().max(100).optional(),
    action: z.enum(['view', 'copy', 'call']).default('view'),
  })
  .strict();
export type RevealInput = z.infer<typeof revealInputSchema>;

/** Hours offered by "Xin quyền truy cập" (MH-PQ-11 #3): 4 giờ / 1 ngày / 3 ngày / 7 ngày. */
export const GRANT_DURATION_HOURS = [4, 24, 72, 168] as const;

/** `POST /api/access-grants` (MH-PQ-11): ask for temporary access to one conversation. */
export const grantRequestInputSchema = z
  .object({
    /** Conversation id `${uid}:${threadId}`. */
    targetId: z.string().min(3).max(400),
    /** Highest right asked: xem ⊂ ghi_chu ⊂ tra_loi. */
    right: z.enum(GRANT_RIGHTS).default('xem'),
    durationHours: z.number().int().refine((h) => (GRANT_DURATION_HOURS as readonly number[]).includes(h), 'Thời hạn không hợp lệ').default(24),
    reason: z.string().trim().min(10, 'Lý do cần 10–300 ký tự').max(300, 'Lý do cần 10–300 ký tự'),
  })
  .strict();
export type GrantRequestInput = z.infer<typeof grantRequestInputSchema>;

/** Answer of `GET /api/access-grants/approver` and `POST /api/access-grants`. */
export interface GrantApproverView {
  approverId: string | null;
  approverName: string | null;
  /** Reply on the nick of a personal channel is locked (PQ-31). */
  replyLocked: boolean;
}

/** `GET /api/conversations/:id/access`: what the signed-in user may do in one conversation (D8-02). */
export interface ConversationAccess {
  canReply: boolean;
  /** Why not (tooltip / replacement of the compose box); null when allowed. */
  replyReason: string | null;
  /**
   * How a reply goes out (QT-SZ-10, M1b-10): on the user's own nick (null), as the active cover of the
   * absent holder (green strip), or replying on behalf of the holder (yellow strip, always confirmed).
   */
  sendMode?: 'truc_thay' | 'tra_loi_thay' | null;
  /** Nick holder's name ({ten_nguoi_giu_nick}); null when nobody holds it or for official channels. */
  holderName?: string | null;
  /** Nick label shown in the strip. */
  nickLabel?: string | null;
  /** truc_thay: end of the cover (ISO). */
  coverUntil?: string | null;
  /**
   * SZ-23 / D24: opening the conversation may ask Zalo Web for missing content and mark it read only
   * when the viewer holds the nick (or covers it). Others never trigger "Đã xem".
   */
  autoFetch?: boolean;
  /** GS / GĐ (reply on behalf) may still fetch on purpose, confirmed and logged (`conversation.fetch_on_behalf`). */
  canFetchOnBehalf?: boolean;
}

// <generated:permissions> — node tools/authz/gen-permissions.js
/* eslint-disable */
/** Every permission key of the spec §3, in spec order. */
export const PERMISSION_KEYS = [
  "conv.view",
  "conv.view_unassigned",
  "conv.reply",
  "conv.reply_on_behalf",
  "conv.claim",
  "conv.assign",
  "conv.transfer",
  "conv.status",
  "conv.note",
  "conv.label",
  "msg.attachment",
  "outbox.reapprove",
  "conv.fetch_on_behalf",
  "msg.recall",
  "msg.react",
  "msg.delete",
  "conv.delete",
  "ai.draft",
  "search.global",
  "conv.mark_sample",
  "cust.view",
  "cust.timeline",
  "cust.commerce",
  "cust.debt",
  "cust.ai_summary",
  "cust.edit",
  "cust.merge",
  "cust.split",
  "cust.erp_link",
  "cust.related_account",
  "erp_task.merge_codes",
  "cust.import",
  "cust.transfer_request",
  "cust.transfer_approve",
  "cust.handover",
  "cust.reclaim",
  "cust.phone_full",
  "cust.commitments",
  "cust.link_provisional",
  "billing_profile.edit",
  "billing_contact.edit",
  "cust.export",
  "cust.export_phone",
  "export.approve",
  "privacy.intake",
  "cust.privacy_request",
  "cust.privacy_execute",
  "erp.lookup",
  "quote.view",
  "quote.open_erp",
  "quote.propose",
  "workitem.submit",
  "workitem.approve",
  "workitem.return",
  "workitem.queue_config",
  "quote.send",
  "invoice.view",
  "invoice_req.create",
  "invoice_req.process",
  "invoice.attach",
  "payment_reply.process",
  "debt.hold",
  "debt.notice.respond",
  "debt.note",
  "debt.urgent_send",
  "statement.confirm",
  "billing_contact.import",
  "invoice_settings.edit",
  "invoice.send",
  "ticket.create",
  "ticket.view",
  "ticket.assign",
  "ticket.resolve",
  "reminder.own",
  "reminder.assign",
  "visit.propose",
  "template.use",
  "template.personal",
  "template.personal_view",
  "template.group_propose",
  "template.group_manage",
  "template.company",
  "template.auto_approve",
  "template.bank",
  "media.use",
  "media.manage",
  "media.delete",
  "zns_template.edit",
  "zns_template.approve",
  "zns.send_single",
  "campaign.create",
  "campaign.approve",
  "campaign.run",
  "campaign.report",
  "cost.view",
  "cost.edit_actual",
  "ads.connect",
  "ads.manage",
  "ads.spend",
  "ads.spend_lock",
  "ads.spend_unlock",
  "lead.view",
  "lead.route",
  "lead.card",
  "lead.dispute",
  "bot.edit",
  "bot.publish",
  "bot.kill",
  "automation.edit",
  "channel.connect",
  "channel.device",
  "channel.status",
  "channel.access",
  "sync.view",
  "mapping.approve",
  "friend.respond",
  "group.manage",
  "friend.block",
  "device.pair",
  "channel.confirm",
  "channel.safety_confirm",
  "org.view",
  "org.edit",
  "user.view",
  "user.edit",
  "user.import",
  "role.approve",
  "user.lock",
  "user.pre_leave",
  "user.offboard",
  "user.handover",
  "permission.explain",
  "access.review",
  "role.view",
  "role.edit",
  "grant.request",
  "grant.approve",
  "grant.cover",
  "grant.leave_request",
  "grant.delegate",
  "grant.revoke",
  "token.own",
  "token.manage",
  "audit.view",
  "alert.handle",
  "alert.config",
  "config.sla",
  "config.routing_propose",
  "config.report_target",
  "config.abandon",
  "config.retention",
  "config.security",
  "report.volume",
  "report.performance",
  "report.source",
  "report.care",
  "report.data_quality",
  "report.ticket",
  "report.invoice",
  "report.export",
  "report.turn_note",
  "report.turn_adjust_request",
  "report.turn_adjust_decide",
  "report.snapshot_accept",
] as const;
export type PermissionKey = (typeof PERMISSION_KEYS)[number];

/** Label ("Chức năng") and spec section of each key, for the role matrix screen (MH-PQ-05). */
export const PERMISSION_INFO: Record<PermissionKey, { label: string; section: string }> = {
  "conv.view": { label: "Xem danh sách & nội dung hội thoại", section: "3.1 Hội thoại & tin nhắn" },
  "conv.view_unassigned": { label: "Xem hàng \"Chưa phân công\"", section: "3.1 Hội thoại & tin nhắn" },
  "conv.reply": { label: "Trả lời (gửi tin, gửi nháp AI đã duyệt)", section: "3.1 Hội thoại & tin nhắn" },
  "conv.reply_on_behalf": { label: "Trả lời thay (hội thoại người khác phụ trách)", section: "3.1 Hội thoại & tin nhắn" },
  "conv.claim": { label: "Nhận hội thoại chưa phân công (nút \"Nhận\" / \"Nhận hội thoại này\" theo 00)", section: "3.1 Hội thoại & tin nhắn" },
  "conv.assign": { label: "Phân công / chia hội thoại", section: "3.1 Hội thoại & tin nhắn" },
  "conv.transfer": { label: "Chuyển hội thoại cho người / nhóm khác (có lý do)", section: "3.1 Hội thoại & tin nhắn" },
  "conv.status": { label: "Đổi trạng thái (Mới / Đang xử lý / Chờ khách / Đã xong)", section: "3.1 Hội thoại & tin nhắn" },
  "conv.note": { label: "Ghi chú nội bộ, @nhắc đồng nghiệp", section: "3.1 Hội thoại & tin nhắn" },
  "conv.label": { label: "Ghim, gắn nhãn, đánh dấu đã đọc / chưa đọc", section: "3.1 Hội thoại & tin nhắn" },
  "msg.attachment": { label: "Tải đính kèm, nghe ghi âm, đọc bản chữ ghi âm", section: "3.1 Hội thoại & tin nhắn" },
  "outbox.reapprove": { label: "Duyệt lại lệnh gửi Cần duyệt lại", section: "3.1 Hội thoại & tin nhắn" },
  "conv.fetch_on_behalf": { label: "Lấy nội dung tin trên nick người khác (khách sẽ thấy \"Đã xem\")", section: "3.1 Hội thoại & tin nhắn" },
  "msg.recall": { label: "Thu hồi tin trên nền tảng (Zalo, Messenger)", section: "3.1 Hội thoại & tin nhắn" },
  "msg.react": { label: "Thả cảm xúc, trả lời trích dẫn, @nhắc tên thành viên nhóm", section: "3.1 Hội thoại & tin nhắn" },
  "msg.delete": { label: "Xóa tin khỏi VClinks", section: "3.1 Hội thoại & tin nhắn" },
  "conv.delete": { label: "Xóa hội thoại khỏi VClinks", section: "3.1 Hội thoại & tin nhắn" },
  "ai.draft": { label: "Xem nháp AI, bấm \"Soạn nháp\"", section: "3.1 Hội thoại & tin nhắn" },
  "search.global": { label: "Tìm kiếm toàn cục (tên, SĐT, nội dung, mã OE, VIN)", section: "3.1 Hội thoại & tin nhắn" },
  "conv.mark_sample": { label: "Đánh dấu hội thoại \"mẫu\" gửi VCwiki (F15.13)", section: "3.1 Hội thoại & tin nhắn" },
  "cust.view": { label: "Xem hồ sơ khách (đầu trang, người liên hệ, kênh, tag, phễu)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.timeline": { label: "Xem dòng thời gian 360", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.commerce": { label: "Khối thương mại: báo giá, đơn, doanh số, hạng", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.debt": { label: "Công nợ, hạn thanh toán", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.ai_summary": { label: "Khối AI (tóm tắt nhu cầu, khiếu nại mở)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.edit": { label: "Sửa thông tin khách (tên gợi nhớ, loại, khu vực, tag, phễu, người liên hệ)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.merge": { label: "Duyệt gợi ý gộp, gộp tay", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.split": { label: "Tách hồ sơ đã gộp", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.erp_link": { label: "Liên kết / gỡ mã KH ERP", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.related_account": { label: "Ghi account liên quan (cùng chủ) từ gợi ý gộp bị chặn vì hai mã KH (02 MH-DK-05 \"Là account liên quan (cùng chủ)\", DK-55)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "erp_task.merge_codes": { label: "Báo trùng mã trên VCsales: chọn mã chính, tạo việc merge_codes ở 02 MH-DK-12 (02 MH-DK-05 \"Báo trùng trên VCsales\")", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.import": { label: "Nhập khách từ CSV", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.transfer_request": { label: "Gửi yêu cầu chuyển khách", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.transfer_approve": { label: "Duyệt yêu cầu chuyển khách", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.handover": { label: "Bàn giao / đổi owner (đơn lẻ, cả lô)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.reclaim": { label: "Thu hồi khách bị bỏ rơi về \"Chưa phân công\"", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.phone_full": { label: "Xem SĐT / email đầy đủ", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.commitments": { label: "Khối \"Cam kết đã nêu (7 ngày)\" (02 DK-49)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.link_provisional": { label: "\"Tạm gắn để xem\" khách của người khác (02 DK-51)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "billing_profile.edit": { label: "Hồ sơ xuất hóa đơn: thêm, sửa, ngừng dùng (06 MH-HD-09)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "billing_contact.edit": { label: "Người liên hệ thanh toán, cờ nhận nhắc nợ / hóa đơn (06 MH-HD-09)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.export": { label: "Xuất danh sách khách (Excel)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.export_phone": { label: "Xuất kèm SĐT đầy đủ", section: "3.2 Khách hàng, danh tính & SĐT" },
  "export.approve": { label: "Duyệt yêu cầu xuất kèm SĐT", section: "3.2 Khách hàng, danh tính & SĐT" },
  "privacy.intake": { label: "Ghi nhận yêu cầu dữ liệu cá nhân của khách (NĐ 13)", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.privacy_request": { label: "Tạo / xử lý phiếu NĐ 13, xác nhận \"đúng khách\"", section: "3.2 Khách hàng, danh tính & SĐT" },
  "cust.privacy_execute": { label: "Thực hiện xuất / xóa theo yêu cầu khách", section: "3.2 Khách hàng, danh tính & SĐT" },
  "erp.lookup": { label: "Tra nhanh giá, tồn (VCsales)", section: "3.3 Bán hàng & chăm sóc" },
  "quote.view": { label: "Xem báo giá của khách", section: "3.3 Bán hàng & chăm sóc" },
  "quote.open_erp": { label: "Mở VCsales để tạo báo giá (F9.2)", section: "3.3 Bán hàng & chăm sóc" },
  "quote.propose": { label: "Xem, sửa đề xuất báo giá của AI; tạo đề xuất tay (BA F9.14)", section: "3.3 Bán hàng & chăm sóc" },
  "workitem.submit": { label: "Chuyển phiếu sang \"Chờ NVKD duyệt\" (gắn báo giá đã duyệt / câu trả lời hậu mãi + lời nhắn)", section: "3.3 Bán hàng & chăm sóc" },
  "workitem.approve": { label: "Duyệt & gửi phiếu trên nick cá nhân (bấm = duyệt lệnh gửi qua nick)", section: "3.3 Bán hàng & chăm sóc" },
  "workitem.return": { label: "Trả lại phiếu cho CSKH (bắt buộc lý do)", section: "3.3 Bán hàng & chăm sóc" },
  "workitem.queue_config": { label: "Cấu hình hàng việc CSKH (ai ở hàng Bán hàng / Hậu mãi, cách chia)", section: "3.3 Bán hàng & chăm sóc" },
  "quote.send": { label: "Gửi báo giá cho khách (BR16, BR17)", section: "3.3 Bán hàng & chăm sóc" },
  "invoice.view": { label: "Xem hóa đơn VAT", section: "3.3 Bán hàng & chăm sóc" },
  "invoice_req.create": { label: "Tạo phiếu yêu cầu xuất hóa đơn", section: "3.3 Bán hàng & chăm sóc" },
  "invoice_req.process": { label: "Xử lý phiếu (đã xuất / từ chối) (06 MH-HD-03)", section: "3.3 Bán hàng & chăm sóc" },
  "invoice.attach": { label: "Gắn / gỡ hóa đơn với phiếu, đơn", section: "3.3 Bán hàng & chăm sóc" },
  "payment_reply.process": { label: "Phản hồi thanh toán: xem, đối chiếu, trả lời khách bằng mẫu \"Thanh toán\" (06 MH-HD-08)", section: "3.3 Bán hàng & chăm sóc" },
  "debt.hold": { label: "Tạm hoãn nhắc nợ của khách", section: "3.3 Bán hàng & chăm sóc" },
  "debt.notice.respond": { label: "Trả lời báo trước nhắc nợ: \"Đồng ý\" / \"Tôi tự nhắc\" / \"Xin giữ lại\" (06 MH-HD-13, HD-51)", section: "3.3 Bán hàng & chăm sóc" },
  "debt.note": { label: "Ghi chú thu nợ trên account: thêm / đọc (06 HD-56)", section: "3.3 Bán hàng & chăm sóc" },
  "debt.urgent_send": { label: "\"Gửi gấp\" nhắc lẻ bỏ qua khoảng chờ báo trước, có lý do (06 HD-51 d)", section: "3.3 Bán hàng & chăm sóc" },
  "statement.confirm": { label: "Xác nhận mốc sao kê \"Đã ghi sao kê tới {giờ}\" (06 HD-50)", section: "3.3 Bán hàng & chăm sóc" },
  "billing_contact.import": { label: "Nạp người nhận thanh toán hàng loạt từ VCsales / Excel (06 MH-HD-12, HD-48)", section: "3.3 Bán hàng & chăm sóc" },
  "invoice_settings.edit": { label: "Cấu hình hóa đơn, ngưỡng nhắc (06, /admin/invoice-settings)", section: "3.3 Bán hàng & chăm sóc" },
  "invoice.send": { label: "Gửi hóa đơn cho khách (06 MH-HD-05)", section: "3.3 Bán hàng & chăm sóc" },
  "ticket.create": { label: "Tạo ticket từ tin nhắn", section: "3.3 Bán hàng & chăm sóc" },
  "ticket.view": { label: "Xem ticket", section: "3.3 Bán hàng & chăm sóc" },
  "ticket.assign": { label: "Phân công ticket", section: "3.3 Bán hàng & chăm sóc" },
  "ticket.resolve": { label: "Xử lý, đóng ticket", section: "3.3 Bán hàng & chăm sóc" },
  "reminder.own": { label: "Nhắc việc (tạo cho mình / xem)", section: "3.3 Bán hàng & chăm sóc" },
  "reminder.assign": { label: "Giao nhắc việc cho người khác", section: "3.3 Bán hàng & chăm sóc" },
  "visit.propose": { label: "Đề xuất lịch ghé thăm (VCdms)", section: "3.3 Bán hàng & chăm sóc" },
  "template.use": { label: "Dùng mẫu câu (gõ /)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.personal": { label: "Mẫu câu cá nhân: tạo / sửa / xóa của mình", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.personal_view": { label: "Mẫu câu cá nhân của thành viên: xem (chỉ đọc)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.group_propose": { label: "Mẫu câu nhóm: đề xuất", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.group_manage": { label: "Mẫu câu nhóm: duyệt, sửa, xóa", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.company": { label: "Mẫu câu công ty (theo division): tạo, sửa, xóa", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.auto_approve": { label: "Duyệt mẫu câu dùng cho tin tự động (quy tắc tự động, tự trả lời bình luận)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "template.bank": { label: "Mẫu số tài khoản ngân hàng", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "media.use": { label: "Thư viện media: xem, chèn vào tin", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "media.manage": { label: "Thư viện media: tải lên, sửa", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "media.delete": { label: "Thư viện media: xóa", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "zns_template.edit": { label: "Mẫu ZNS: soạn, gửi Zalo duyệt", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "zns_template.approve": { label: "Mẫu ZNS: duyệt nội bộ trước khi dùng", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "zns.send_single": { label: "Gửi tin mẫu (ZNS) lẻ cho 1 khách (04 MH-OA-12; MVP hay GĐ2 chờ QĐ-03)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "campaign.create": { label: "Chiến dịch (ZNS, tin OA, Fanpage): tạo, sửa nháp", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "campaign.approve": { label: "Chiến dịch: duyệt", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "campaign.run": { label: "Chiến dịch: bắt đầu gửi / tạm dừng", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "campaign.report": { label: "Chiến dịch: xem kết quả (04 MH-OA-14)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "cost.view": { label: "Chi phí tin mẫu: xem, xuất (04 MH-OA-19)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "cost.edit_actual": { label: "Chi phí tin mẫu: nhập chi phí thực (04 MH-OA-19)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "ads.connect": { label: "Tài khoản quảng cáo (Zalo Ads, Meta Ads): kết nối", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "ads.manage": { label: "Quảng cáo, form lead: xem hiệu quả, gắn nguồn", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "ads.spend": { label: "Chi phí quảng cáo: nhập (05 MH-MK-10; chờ QĐ-62, mặc định B)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "ads.spend_lock": { label: "Chi phí quảng cáo: khóa kỳ", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "ads.spend_unlock": { label: "Chi phí quảng cáo: mở khóa kỳ, có lý do", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "lead.view": { label: "Hàng \"Lead chưa giao\": xem nội dung", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "lead.route": { label: "Giao lead cho tổ / \"Chưa phân công\" của tổ", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "lead.card": { label: "Thẻ lead rút gọn (lead đã giao; lead từ nick cá nhân)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "lead.dispute": { label: "\"Không đồng ý\" đánh giá lead của sale (Kém / Không hợp lệ) (chờ QĐ-28)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "bot.edit": { label: "Chatbot, tin chào / ngoài giờ (OA, Fanpage, web): soạn kịch bản", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "bot.publish": { label: "Chatbot, tin chào / ngoài giờ: duyệt & xuất bản (chờ QĐ-26; mặc định GĐ)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "bot.kill": { label: "Chatbot: tắt khẩn cấp", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "automation.edit": { label: "Quy tắc tự động (F7.5; 04 MH-OA-10)", section: "3.4 Nội dung, chiến dịch, quảng cáo & chatbot" },
  "channel.connect": { label: "Kết nối / ngắt kênh API (OA, Fanpage, Gmail, chatbot web)", section: "3.5 Kênh & kỹ thuật" },
  "channel.device": { label: "Khai báo nick cá nhân, cấp token thiết bị", section: "3.5 Kênh & kỹ thuật" },
  "channel.status": { label: "Xem trạng thái kênh (xanh / vàng / đỏ)", section: "3.5 Kênh & kỹ thuật" },
  "channel.access": { label: "Gán kênh cho người / đơn vị", section: "3.5 Kênh & kỹ thuật" },
  "sync.view": { label: "Đối chiếu đồng bộ (số bản ghi nguồn so với VClinks)", section: "3.5 Kênh & kỹ thuật" },
  "mapping.approve": { label: "Bảng ánh xạ trường: xem, duyệt đề xuất", section: "3.5 Kênh & kỹ thuật" },
  "friend.respond": { label: "Lời mời kết bạn: chấp nhận / từ chối", section: "3.5 Kênh & kỹ thuật" },
  "group.manage": { label: "Tạo nhóm Zalo, thêm / mời thành viên", section: "3.5 Kênh & kỹ thuật" },
  "friend.block": { label: "Chặn / hủy kết bạn trên nick (03 MH-SZ-09; chờ QĐ-31, mặc định B)", section: "3.5 Kênh & kỹ thuật" },
  "device.pair": { label: "Ghép thiết bị bằng mã, xoay vòng / thu hồi token thiết bị", section: "3.5 Kênh & kỹ thuật" },
  "channel.confirm": { label: "Xác nhận / từ chối \"Nick chờ xác nhận\" (thiết bị đăng ký nick mới)", section: "3.5 Kênh & kỹ thuật" },
  "channel.safety_confirm": { label: "Xác nhận nick đã đăng xuất trên thiết bị cũ (bỏ \"Chưa an toàn\", PQ-51; chờ QĐ-11)", section: "3.5 Kênh & kỹ thuật" },
  "org.view": { label: "Xem cây tổ chức", section: "3.6 Quản trị" },
  "org.edit": { label: "Sửa cây tổ chức (thêm / đổi / ngừng đơn vị, đặt quản lý)", section: "3.6 Quản trị" },
  "user.view": { label: "Xem danh sách người dùng", section: "3.6 Quản trị" },
  "user.edit": { label: "Tạo, sửa người dùng, gán vai trò, đổi vị trí", section: "3.6 Quản trị" },
  "user.import": { label: "Nhập lô người dùng (file, Google Workspace)", section: "3.6 Quản trị" },
  "role.approve": { label: "Duyệt thay đổi vai trò nhạy cảm (người thứ hai)", section: "3.6 Quản trị" },
  "user.lock": { label: "Tạm khóa / mở khóa tài khoản", section: "3.6 Quản trị" },
  "user.pre_leave": { label: "Đặt / bỏ cờ \"Sắp nghỉ\"", section: "3.6 Quản trị" },
  "user.offboard": { label: "Đánh dấu nghỉ việc (khóa ngay)", section: "3.6 Quản trị" },
  "user.handover": { label: "Bàn giao khách của người nghỉ việc", section: "3.6 Quản trị" },
  "permission.explain": { label: "Kiểm tra \"vì sao thấy / không thấy\" (tra theo tên, mã, SĐT)", section: "3.6 Quản trị" },
  "access.review": { label: "Soát quyền định kỳ", section: "3.6 Quản trị" },
  "role.view": { label: "Xem vai trò & ma trận quyền", section: "3.6 Quản trị" },
  "role.edit": { label: "Tạo vai trò tùy chỉnh, sửa quyền (dưới trần)", section: "3.6 Quản trị" },
  "grant.request": { label: "Xin quyền tạm thời", section: "3.6 Quản trị" },
  "grant.approve": { label: "Duyệt quyền tạm thời", section: "3.6 Quản trị" },
  "grant.cover": { label: "Tạo \"Trực thay\"", section: "3.6 Quản trị" },
  "grant.leave_request": { label: "Gửi \"Đăng ký vắng\" (đề xuất trực thay cho mình)", section: "3.6 Quản trị" },
  "grant.delegate": { label: "Ủy quyền duyệt có thời hạn", section: "3.6 Quản trị" },
  "grant.revoke": { label: "Thu hồi quyền tạm thời trước hạn", section: "3.6 Quản trị" },
  "token.own": { label: "Token MCP của tôi: tạo, thu hồi", section: "3.6 Quản trị" },
  "token.manage": { label: "Xem / thu hồi token của người khác; tạo token đồng bộ, tác tử gửi, thiết bị", section: "3.6 Quản trị" },
  "audit.view": { label: "Nhật ký truy cập", section: "3.6 Quản trị" },
  "alert.handle": { label: "Xem & xử lý cảnh báo bất thường", section: "3.6 Quản trị" },
  "alert.config": { label: "Cấu hình quy tắc cảnh báo", section: "3.6 Quản trị" },
  "config.sla": { label: "Cấu hình SLA, lịch làm việc division, quy tắc chia khách (màn 04 MH-OA-18 và 07 MH-RT-01…06; route theo 00 §2)", section: "3.6 Quản trị" },
  "config.routing_propose": { label: "Gửi / rút đề xuất thay đổi quy tắc chia khách (07 MH-RT-04; GĐ duyệt bằng config.sla DV)", section: "3.6 Quản trị" },
  "config.report_target": { label: "Đặt / sửa mục tiêu báo cáo division (KPI-05, 06, 12; theo tổ tùy chọn — 07 BC-29 b, MH-RT-06 #10). Chỉ tiêu tập đoàn G1–G6: QS đề xuất, chủ dự án chốt (QĐ-94), GĐ chỉ đọc", section: "3.6 Quản trị" },
  "config.abandon": { label: "Cấu hình \"khách bị bỏ rơi\" (30/60/90 ngày)", section: "3.6 Quản trị" },
  "config.retention": { label: "Thời hạn lưu trữ (NĐ 13)", section: "3.6 Quản trị" },
  "config.security": { label: "Cài đặt bảo mật (token tự tạo, hạn quyền tạm thời)", section: "3.6 Quản trị" },
  "report.volume": { label: "Lượng hội thoại, heatmap giờ (F10.1)", section: "3.7 Báo cáo & xuất" },
  "report.performance": { label: "Hiệu suất nhân viên (F10.2)", section: "3.7 Báo cáo & xuất" },
  "report.source": { label: "Nguồn khách, quảng cáo → lead → đơn (F10.3)", section: "3.7 Báo cáo & xuất" },
  "report.care": { label: "Chăm sóc: mua lại, bỏ rơi, báo giá treo (F15.7)", section: "3.7 Báo cáo & xuất" },
  "report.data_quality": { label: "Chất lượng dữ liệu (F15.8)", section: "3.7 Báo cáo & xuất" },
  "report.ticket": { label: "Ticket, khảo sát hài lòng", section: "3.7 Báo cáo & xuất" },
  "report.invoice": { label: "Hóa đơn: yêu cầu → phát hành → đã gửi khách (06 MH-HD-10)", section: "3.7 Báo cáo & xuất" },
  "report.export": { label: "Xuất Excel báo cáo (số liệu tổng hợp, không SĐT)", section: "3.7 Báo cáo & xuất" },
  "report.turn_note": { label: "Ghi giải trình trên lượt chờ (07 BC-26)", section: "3.7 Báo cáo & xuất" },
  "report.turn_adjust_request": { label: "Gửi đề nghị tính lại lượt (07 BC-26)", section: "3.7 Báo cáo & xuất" },
  "report.turn_adjust_decide": { label: "Duyệt / từ chối đề nghị tính lại lượt (07 BC-26; không tự duyệt, PQ-27)", section: "3.7 Báo cáo & xuất" },
  "report.snapshot_accept": { label: "Chấp nhận / không chấp nhận bản chụp bổ sung (07 BC-15 d, MH-BC-09)", section: "3.7 Báo cáo & xuất" },
};

/** System roles → key → cell. Keys absent for a role are ✖. */
export const ROLE_MATRIX: Record<RoleKey, Partial<Record<PermissionKey, PermCell>>> = {
  admin: {
    "conv.view": { s: ["YC"], log: true },
    "msg.attachment": { s: ["YC"], log: true },
    "msg.delete": { s: ["ALL"], log: true },
    "conv.delete": { s: ["ALL"], log: true },
    "search.global": { s: ["YC"], log: true },
    "privacy.intake": { s: ["ALL"] },
    "cust.privacy_request": { s: ["ALL"], cond: "no_content" },
    "cust.privacy_execute": { s: ["ALL"], log: true },
    "invoice_settings.edit": { s: ["ALL"], cond: "integration_only" },
    "cost.view": { s: ["TD"], mode: "view" },
    "ads.connect": { s: ["ALL"] },
    "bot.kill": { s: ["ALL"] },
    "channel.connect": { s: ["ALL"] },
    "channel.device": { s: ["ALL"] },
    "channel.status": { s: ["TD"] },
    "channel.access": { s: ["TD"] },
    "sync.view": { s: ["TD"] },
    "mapping.approve": { s: ["ALL"] },
    "device.pair": { s: ["ALL"] },
    "channel.confirm": { s: ["ALL"] },
    "channel.safety_confirm": { s: ["ALL"] },
    "org.view": { s: ["TD"] },
    "org.edit": { s: ["ALL"] },
    "user.view": { s: ["TD"] },
    "user.edit": { s: ["ALL"], notSelf: true },
    "user.import": { s: ["ALL"] },
    "user.lock": { s: ["ALL"] },
    "user.pre_leave": { s: ["ALL"] },
    "user.offboard": { s: ["ALL"] },
    "user.handover": { s: ["ALL"] },
    "permission.explain": { s: ["TD"] },
    "access.review": { s: ["TD"], mode: "propose" },
    "role.view": { s: ["ALL"] },
    "role.edit": { s: ["ALL"] },
    "grant.request": { s: ["ALL"] },
    "grant.revoke": { s: ["TD"] },
    "token.own": { s: ["ALL"] },
    "token.manage": { s: ["ALL"] },
    "audit.view": { s: ["TD"] },
    "alert.handle": { s: ["TD"], cond: "technical_alerts" },
    "alert.config": { s: ["ALL"] },
    "config.sla": { s: ["ALL"], mode: "view" },
    "config.retention": { s: ["ALL"], mode: "propose" },
    "config.security": { s: ["ALL"] },
    "report.volume": { s: ["TD"] },
    "report.data_quality": { s: ["TD"] },
    "report.export": { s: ["TD"] },
  },
  giam_doc_bh: {
    "conv.view": { s: ["DV"] },
    "conv.view_unassigned": { s: ["DV"] },
    "conv.reply": { s: ["DV"] },
    "conv.reply_on_behalf": { s: ["DV"] },
    "conv.claim": { s: ["DV"] },
    "conv.assign": { s: ["DV"] },
    "conv.transfer": { s: ["DV"] },
    "conv.status": { s: ["DV"] },
    "conv.note": { s: ["DV"] },
    "conv.label": { s: ["DV"] },
    "msg.attachment": { s: ["DV"] },
    "outbox.reapprove": { s: ["NICK"] },
    "conv.fetch_on_behalf": { s: ["DV"], log: true },
    "msg.recall": { s: ["SELF","NICK"] },
    "msg.react": { s: ["DV"] },
    "ai.draft": { s: ["DV"] },
    "search.global": { s: ["DV"] },
    "conv.mark_sample": { s: ["DV"] },
    "cust.view": { s: ["DV"] },
    "cust.timeline": { s: ["DV"] },
    "cust.commerce": { s: ["DV"] },
    "cust.debt": { s: ["DV"] },
    "cust.ai_summary": { s: ["DV"] },
    "cust.edit": { s: ["DV"] },
    "cust.merge": { s: ["DV"] },
    "cust.split": { s: ["DV"] },
    "cust.erp_link": { s: ["DV"] },
    "cust.import": { s: ["DV"] },
    "cust.transfer_approve": { s: ["DV"] },
    "cust.handover": { s: ["DV"] },
    "cust.reclaim": { s: ["DV"] },
    "cust.phone_full": { s: ["CT","NICK"], log: true, reveal: ["DV"] },
    "cust.commitments": { s: ["DV"] },
    "cust.link_provisional": { s: ["DV"] },
    "cust.export": { s: ["DV"], log: true },
    "cust.export_phone": { s: ["DV"], log: true, mode: "request" },
    "privacy.intake": { s: ["DV"] },
    "cust.privacy_request": { s: ["DV"] },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["DV"] },
    "quote.open_erp": { s: ["DV"] },
    "quote.propose": { s: ["DV"] },
    "workitem.approve": { s: ["DV"], cond: "on_behalf" },
    "workitem.return": { s: ["DV"] },
    "workitem.queue_config": { s: ["DV"] },
    "quote.send": { s: ["DV"] },
    "invoice.view": { s: ["DV"] },
    "invoice_req.create": { s: ["DV"] },
    "payment_reply.process": { s: ["DV"], mode: "view" },
    "debt.hold": { s: ["DV"] },
    "debt.note": { s: ["DV"] },
    "invoice_settings.edit": { s: ["DV"] },
    "invoice.send": { s: ["DV"] },
    "ticket.create": { s: ["DV"] },
    "ticket.view": { s: ["DV"] },
    "ticket.assign": { s: ["DV"] },
    "ticket.resolve": { s: ["DV"] },
    "reminder.own": { s: ["ALL"] },
    "reminder.assign": { s: ["DV"] },
    "visit.propose": { s: ["DV"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.group_manage": { s: ["DV"] },
    "template.company": { s: ["DV"] },
    "template.auto_approve": { s: ["DV"] },
    "template.bank": { s: ["DV"] },
    "media.use": { s: ["ALL"] },
    "media.manage": { s: ["DV"] },
    "media.delete": { s: ["DV"] },
    "zns_template.edit": { s: ["DV"] },
    "zns_template.approve": { s: ["DV"] },
    "campaign.create": { s: ["DV"] },
    "campaign.approve": { s: ["DV"] },
    "campaign.run": { s: ["DV"] },
    "campaign.report": { s: ["DV"] },
    "cost.view": { s: ["DV"] },
    "ads.manage": { s: ["DV"] },
    "ads.spend_unlock": { s: ["DV"] },
    "lead.view": { s: ["DV"] },
    "lead.route": { s: ["DV"] },
    "lead.card": { s: ["DV"] },
    "lead.dispute": { s: ["DV"] },
    "bot.edit": { s: ["DV"] },
    "bot.publish": { s: ["DV"] },
    "bot.kill": { s: ["DV"] },
    "automation.edit": { s: ["DV"], cond: "toggle_only" },
    "channel.status": { s: ["DV"] },
    "channel.access": { s: ["DV"] },
    "sync.view": { s: ["DV"] },
    "friend.respond": { s: ["NICK"] },
    "group.manage": { s: ["NICK"] },
    "friend.block": { s: ["DV"], log: true },
    "channel.confirm": { s: ["DV"], mode: "view" },
    "channel.safety_confirm": { s: ["DV"] },
    "org.view": { s: ["DV"] },
    "user.view": { s: ["DV"] },
    "user.lock": { s: ["DV"] },
    "user.pre_leave": { s: ["DV"] },
    "user.offboard": { s: ["DV"] },
    "user.handover": { s: ["DV"] },
    "permission.explain": { s: ["DV"] },
    "access.review": { s: ["DV"] },
    "role.view": { s: ["ALL"] },
    "grant.request": { s: ["ALL"] },
    "grant.approve": { s: ["DV"] },
    "grant.cover": { s: ["DV"] },
    "grant.delegate": { s: ["DV"] },
    "grant.revoke": { s: ["DV"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["DV"] },
    "alert.handle": { s: ["DV"] },
    "alert.config": { s: ["ALL"], mode: "view" },
    "config.sla": { s: ["DV"] },
    "config.report_target": { s: ["DV"] },
    "config.abandon": { s: ["DV"] },
    "report.volume": { s: ["DV"] },
    "report.performance": { s: ["DV"] },
    "report.source": { s: ["DV"] },
    "report.care": { s: ["DV"] },
    "report.data_quality": { s: ["DV"] },
    "report.ticket": { s: ["DV"] },
    "report.invoice": { s: ["DV"] },
    "report.export": { s: ["DV"], log: true },
    "report.turn_adjust_decide": { s: ["DV"] },
  },
  giam_sat_bh: {
    "conv.view": { s: ["TO"] },
    "conv.view_unassigned": { s: ["TO"] },
    "conv.reply": { s: ["TO"] },
    "conv.reply_on_behalf": { s: ["TO"] },
    "conv.claim": { s: ["TO"] },
    "conv.assign": { s: ["TO"] },
    "conv.transfer": { s: ["TO"] },
    "conv.status": { s: ["TO"] },
    "conv.note": { s: ["TO"] },
    "conv.label": { s: ["TO"] },
    "msg.attachment": { s: ["TO"] },
    "outbox.reapprove": { s: ["NICK"] },
    "conv.fetch_on_behalf": { s: ["TO"], log: true },
    "msg.recall": { s: ["SELF","NICK"] },
    "msg.react": { s: ["TO"] },
    "ai.draft": { s: ["TO"] },
    "search.global": { s: ["TO"] },
    "conv.mark_sample": { s: ["TO"] },
    "cust.view": { s: ["TO"] },
    "cust.timeline": { s: ["TO"] },
    "cust.commerce": { s: ["TO"] },
    "cust.debt": { s: ["TO"] },
    "cust.ai_summary": { s: ["TO"] },
    "cust.edit": { s: ["TO"] },
    "cust.merge": { s: ["TO"] },
    "cust.split": { s: ["TO"] },
    "cust.transfer_request": { s: ["TO"], cond: "to_own_team" },
    "cust.transfer_approve": { s: ["TO"] },
    "cust.handover": { s: ["TO"] },
    "cust.reclaim": { s: ["TO"] },
    "cust.phone_full": { s: ["CT","NICK"], log: true, reveal: ["TO"] },
    "cust.commitments": { s: ["TO"] },
    "cust.link_provisional": { s: ["TO"] },
    "privacy.intake": { s: ["TO"] },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["TO"] },
    "quote.open_erp": { s: ["TO"] },
    "quote.propose": { s: ["TO"] },
    "workitem.approve": { s: ["TO"], cond: "on_behalf" },
    "workitem.return": { s: ["TO"] },
    "quote.send": { s: ["TO"] },
    "invoice.view": { s: ["TO"] },
    "invoice_req.create": { s: ["TO"] },
    "debt.hold": { s: ["TO"], mode: "propose" },
    "debt.notice.respond": { s: ["TO"], cond: "owner_absent" },
    "debt.note": { s: ["TO"] },
    "invoice.send": { s: ["TO"] },
    "ticket.create": { s: ["TO"] },
    "ticket.view": { s: ["TO"] },
    "reminder.own": { s: ["ALL"] },
    "reminder.assign": { s: ["TO"] },
    "visit.propose": { s: ["TO"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.personal_view": { s: ["TO"] },
    "template.group_manage": { s: ["TO"] },
    "media.use": { s: ["ALL"] },
    "campaign.report": { s: ["TO"] },
    "lead.card": { s: ["TO"] },
    "lead.dispute": { s: ["TO"] },
    "channel.status": { s: ["TO"] },
    "friend.respond": { s: ["NICK"] },
    "group.manage": { s: ["NICK"] },
    "friend.block": { s: ["NICK","TO"], log: true },
    "channel.safety_confirm": { s: ["NICK"] },
    "org.view": { s: ["TO"] },
    "user.view": { s: ["TO"] },
    "user.lock": { s: ["TO"], cond: "emergency_lock_only" },
    "user.pre_leave": { s: ["TO"] },
    "user.handover": { s: ["TO"] },
    "permission.explain": { s: ["TO"] },
    "role.view": { s: ["ALL"] },
    "grant.request": { s: ["ALL"] },
    "grant.approve": { s: ["TO"] },
    "grant.cover": { s: ["TO"] },
    "grant.leave_request": { s: ["ALL"] },
    "grant.delegate": { s: ["TO"] },
    "grant.revoke": { s: ["TO"], cond: "own_approved" },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["TO"] },
    "alert.handle": { s: ["TO"] },
    "config.sla": { s: ["TO"], mode: "view" },
    "config.routing_propose": { s: ["TO"] },
    "report.volume": { s: ["TO"] },
    "report.performance": { s: ["TO"] },
    "report.source": { s: ["TO"] },
    "report.care": { s: ["TO"] },
    "report.invoice": { s: ["TO"] },
    "report.export": { s: ["TO"], log: true },
    "report.turn_note": { s: ["TO"] },
    "report.turn_adjust_request": { s: ["TO"] },
  },
  nvkd: {
    "conv.view": { s: ["CT","NICK"] },
    "conv.view_unassigned": { s: ["TO"] },
    "conv.reply": { s: ["CT","NICK"] },
    "conv.claim": { s: ["TO"] },
    "conv.transfer": { s: ["CT","NICK"], mode: "request" },
    "conv.status": { s: ["CT","NICK"] },
    "conv.note": { s: ["CT","NICK"] },
    "conv.label": { s: ["CT","NICK"] },
    "msg.attachment": { s: ["CT","NICK"] },
    "outbox.reapprove": { s: ["NICK"] },
    "msg.recall": { s: ["NICK"] },
    "msg.react": { s: ["CT","NICK"] },
    "ai.draft": { s: ["CT","NICK"] },
    "search.global": { s: ["CT","NICK"] },
    "cust.view": { s: ["CT","NICK"] },
    "cust.timeline": { s: ["CT"] },
    "cust.commerce": { s: ["CT"] },
    "cust.debt": { s: ["CT"] },
    "cust.ai_summary": { s: ["CT"] },
    "cust.edit": { s: ["CT"] },
    "cust.merge": { s: ["CT"] },
    "cust.transfer_request": { s: ["CT"] },
    "cust.phone_full": { s: ["CT","NICK"] },
    "cust.commitments": { s: ["CT","NICK"] },
    "cust.link_provisional": { s: ["CT","NICK"] },
    "billing_profile.edit": { s: ["CT"] },
    "billing_contact.edit": { s: ["CT"] },
    "privacy.intake": { s: ["CT","NICK"] },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["CT"] },
    "quote.open_erp": { s: ["CT"] },
    "quote.propose": { s: ["CT","NICK"] },
    "workitem.approve": { s: ["NICK"] },
    "workitem.return": { s: ["NICK","CT"] },
    "quote.send": { s: ["CT","NICK"] },
    "invoice.view": { s: ["CT"] },
    "invoice_req.create": { s: ["CT","NICK"] },
    "debt.hold": { s: ["CT"], mode: "propose" },
    "debt.notice.respond": { s: ["CT"] },
    "debt.note": { s: ["CT"] },
    "invoice.send": { s: ["CT","NICK"] },
    "ticket.create": { s: ["CT","NICK"] },
    "ticket.view": { s: ["CT"] },
    "reminder.own": { s: ["ALL"] },
    "visit.propose": { s: ["CT"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.group_propose": { s: ["ALL"] },
    "media.use": { s: ["ALL"] },
    "zns.send_single": { s: ["CT"] },
    "lead.card": { s: ["CT"] },
    "channel.status": { s: ["NICK"] },
    "sync.view": { s: ["NICK"] },
    "friend.respond": { s: ["NICK"] },
    "group.manage": { s: ["NICK"] },
    "channel.safety_confirm": { s: ["NICK"] },
    "grant.request": { s: ["ALL"] },
    "grant.leave_request": { s: ["ALL"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["SELF"] },
    "report.volume": { s: ["CT"] },
    "report.performance": { s: ["CT"] },
    "report.care": { s: ["CT"] },
    "report.turn_note": { s: ["CT"] },
  },
  cskh: {
    "conv.view": { s: ["KENH","TK"] },
    "conv.view_unassigned": { s: ["KENH"] },
    "conv.reply": { s: ["KENH","TK"] },
    "conv.reply_on_behalf": { s: ["NH"] },
    "conv.claim": { s: ["KENH"] },
    "conv.assign": { s: ["NH"] },
    "conv.transfer": { s: ["KENH"] },
    "conv.status": { s: ["KENH","TK"] },
    "conv.note": { s: ["KENH","TK"] },
    "conv.label": { s: ["KENH","TK"] },
    "msg.attachment": { s: ["KENH","TK"] },
    "outbox.reapprove": { s: ["CT"] },
    "msg.recall": { s: ["SELF"] },
    "msg.react": { s: ["KENH","TK"] },
    "ai.draft": { s: ["KENH","TK"] },
    "search.global": { s: ["KENH","TK"] },
    "conv.mark_sample": { s: ["NH"] },
    "cust.view": { s: ["KENH","TK"] },
    "cust.timeline": { s: ["TK"] },
    "cust.commerce": { s: ["TK","KENH"], cond: "orders_only" },
    "cust.ai_summary": { s: ["TK"] },
    "cust.edit": { s: ["TK"], cond: "tag_note_only" },
    "cust.phone_full": { s: ["TK"], log: true, cond: "ticket_open", reveal: ["KENH"] },
    "cust.commitments": { s: ["KENH","TK"] },
    "cust.link_provisional": { s: ["KENH","TK"] },
    "privacy.intake": { s: ["KENH","TK"] },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["TK"] },
    "quote.open_erp": { s: ["TK"] },
    "quote.propose": { s: ["TK"] },
    "workitem.submit": { s: ["TK"] },
    "workitem.queue_config": { s: ["NH"], mode: "propose" },
    "invoice.view": { s: ["TK"] },
    "invoice_req.create": { s: ["TK","KENH"] },
    "ticket.create": { s: ["KENH","TK"] },
    "ticket.view": { s: ["TK"] },
    "ticket.assign": { s: ["NH"] },
    "ticket.resolve": { s: ["TK"] },
    "reminder.own": { s: ["ALL"] },
    "reminder.assign": { s: ["NH"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.group_propose": { s: ["ALL"] },
    "template.group_manage": { s: ["NH"] },
    "media.use": { s: ["ALL"] },
    "zns.send_single": { s: ["KENH","TK"] },
    "campaign.create": { s: ["NH"] },
    "campaign.run": { s: ["SELF"] },
    "campaign.report": { s: ["NH"] },
    "cost.view": { s: ["NH"], mode: "view" },
    "lead.view": { s: ["KENH"] },
    "lead.route": { s: ["KENH"] },
    "bot.edit": { s: ["NH"], mode: "propose" },
    "bot.kill": { s: ["NH"] },
    "automation.edit": { s: ["NH"], cond: "no_activate" },
    "channel.status": { s: ["KENH"] },
    "grant.request": { s: ["ALL"] },
    "grant.cover": { s: ["NH"] },
    "grant.leave_request": { s: ["ALL"] },
    "grant.delegate": { s: ["NH"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["SELF"] },
    "report.volume": { s: ["NH"] },
    "report.performance": { s: ["NH"] },
    "report.ticket": { s: ["NH"] },
    "report.export": { s: ["NH"], log: true },
  },
  marketing: {
    "conv.view": { s: ["LEAD"] },
    "conv.view_unassigned": { s: ["LEAD"] },
    "conv.note": { s: ["LEAD"] },
    "msg.attachment": { s: ["LEAD"] },
    "search.global": { s: ["LEAD"] },
    "cust.view": { s: ["LEAD"] },
    "cust.timeline": { s: ["LEAD"] },
    "cust.edit": { s: ["LEAD"] },
    "cust.import": { s: ["DV"], cond: "lead_only" },
    "cust.phone_full": { s: [], log: true, reveal: ["LEAD"] },
    "cust.export": { s: ["DV"], log: true, cond: "unassigned_leads" },
    "privacy.intake": { s: ["LEAD"] },
    "reminder.own": { s: ["ALL"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.group_propose": { s: ["ALL"] },
    "template.group_manage": { s: ["NH"] },
    "media.use": { s: ["ALL"] },
    "media.manage": { s: ["DV"] },
    "media.delete": { s: ["SELF"] },
    "zns_template.edit": { s: ["DV"] },
    "campaign.create": { s: ["DV"], cond: "purpose_nurture_lead" },
    "campaign.run": { s: ["SELF"], cond: "purpose_nurture_lead" },
    "campaign.report": { s: ["DV"], cond: "purpose_nurture_lead" },
    "ads.manage": { s: ["DV"] },
    "ads.spend": { s: ["DV"] },
    "ads.spend_lock": { s: ["NH"] },
    "lead.view": { s: ["LEAD"] },
    "lead.route": { s: ["LEAD"] },
    "lead.card": { s: ["DV"] },
    "lead.dispute": { s: ["DV"] },
    "bot.edit": { s: ["DV"] },
    "bot.kill": { s: ["DV"] },
    "channel.status": { s: ["KENH"] },
    "grant.request": { s: ["ALL"] },
    "grant.delegate": { s: ["NH"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["SELF"] },
    "report.source": { s: ["DV"] },
    "report.export": { s: ["DV"], log: true },
  },
  sale_admin: {
    "conv.view": { s: ["YC"], log: true },
    "conv.note": { s: ["YC"] },
    "msg.attachment": { s: ["YC"], log: true },
    "search.global": { s: ["YC"], log: true },
    "cust.view": { s: ["DV"] },
    "cust.timeline": { s: ["DV"], cond: "no_messages" },
    "cust.commerce": { s: ["DV"] },
    "cust.debt": { s: ["DV"] },
    "cust.edit": { s: ["DV"] },
    "cust.merge": { s: ["DV"] },
    "cust.split": { s: ["DV"] },
    "cust.erp_link": { s: ["DV"] },
    "cust.related_account": { s: ["DV"] },
    "erp_task.merge_codes": { s: ["DV"] },
    "cust.import": { s: ["DV"] },
    "cust.phone_full": { s: [], log: true, reveal: ["DV"] },
    "billing_profile.edit": { s: ["DV"] },
    "billing_contact.edit": { s: ["DV"] },
    "cust.export": { s: ["DV"], log: true },
    "privacy.intake": { s: ["DV"] },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["DV"] },
    "quote.open_erp": { s: ["DV"] },
    "invoice.view": { s: ["DV"] },
    "invoice_req.create": { s: ["DV"] },
    "debt.note": { s: ["DV"], mode: "view" },
    "billing_contact.import": { s: ["DV"] },
    "reminder.own": { s: ["ALL"] },
    "template.company": { s: ["DV"] },
    "template.bank": { s: ["DV"] },
    "media.use": { s: ["ALL"] },
    "media.manage": { s: ["DV"] },
    "media.delete": { s: ["DV"] },
    "zns_template.edit": { s: ["DV"] },
    "zns.send_single": { s: ["DV"], cond: "order_templates" },
    "campaign.create": { s: ["DV"], cond: "purpose_order_confirm" },
    "campaign.run": { s: ["SELF"] },
    "campaign.report": { s: ["SELF"] },
    "org.view": { s: ["DV"] },
    "grant.request": { s: ["ALL"] },
    "grant.cover": { s: ["NH"] },
    "grant.leave_request": { s: ["ALL"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["SELF"] },
    "report.data_quality": { s: ["DV"] },
    "report.export": { s: ["DV"], log: true },
  },
  ke_toan: {
    "cust.view": { s: ["DV"] },
    "cust.commerce": { s: ["DV"] },
    "cust.debt": { s: ["DV"] },
    "cust.phone_full": { s: [], log: true, cond: "invoice_request", reveal: ["DV"] },
    "billing_profile.edit": { s: ["DV"] },
    "billing_contact.edit": { s: ["DV"] },
    "privacy.intake": { s: ["DV"] },
    "erp.lookup": { s: ["ALL"] },
    "invoice.view": { s: ["DV"] },
    "invoice_req.process": { s: ["DV"] },
    "invoice.attach": { s: ["DV"] },
    "payment_reply.process": { s: ["DV"] },
    "debt.hold": { s: ["DV"] },
    "debt.note": { s: ["DV"] },
    "debt.urgent_send": { s: ["DV"] },
    "statement.confirm": { s: ["DV"] },
    "billing_contact.import": { s: ["DV"] },
    "invoice.send": { s: ["DV"] },
    "reminder.own": { s: ["ALL"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.bank": { s: ["DV"] },
    "media.use": { s: ["ALL"] },
    "zns.send_single": { s: ["DV"], cond: "invoice_payment_templates" },
    "campaign.create": { s: ["DV"], cond: "purpose_payment" },
    "campaign.run": { s: ["SELF"] },
    "campaign.report": { s: ["DV"], cond: "purpose_payment" },
    "cost.view": { s: ["DV"] },
    "cost.edit_actual": { s: ["DV"] },
    "grant.request": { s: ["ALL"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["SELF"] },
    "report.invoice": { s: ["DV"] },
    "report.export": { s: ["DV"], log: true },
  },
  nv_thi_truong: {
    "conv.view": { s: ["TUYEN"] },
    "conv.reply": { s: ["TUYEN"] },
    "conv.status": { s: ["TUYEN"] },
    "conv.note": { s: ["TUYEN"] },
    "conv.label": { s: ["TUYEN"] },
    "msg.attachment": { s: ["TUYEN"] },
    "outbox.reapprove": { s: ["NICK"] },
    "msg.recall": { s: ["SELF","NICK"] },
    "msg.react": { s: ["TUYEN"] },
    "ai.draft": { s: ["TUYEN"] },
    "search.global": { s: ["TUYEN"] },
    "cust.view": { s: ["TUYEN"] },
    "cust.timeline": { s: ["TUYEN"] },
    "cust.commerce": { s: ["TUYEN"] },
    "cust.debt": { s: ["TUYEN"] },
    "cust.ai_summary": { s: ["TUYEN"] },
    "cust.edit": { s: ["TUYEN"], cond: "note_only" },
    "cust.phone_full": { s: ["TUYEN","NICK"] },
    "cust.commitments": { s: ["TUYEN"] },
    "privacy.intake": { s: ["TUYEN"] },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["TUYEN"] },
    "workitem.approve": { s: ["NICK"] },
    "workitem.return": { s: ["NICK"] },
    "invoice.view": { s: ["TUYEN"] },
    "ticket.create": { s: ["TUYEN"] },
    "ticket.view": { s: ["TUYEN"] },
    "reminder.own": { s: ["ALL"] },
    "visit.propose": { s: ["TUYEN"] },
    "template.use": { s: ["ALL"] },
    "template.personal": { s: ["ALL"] },
    "template.group_propose": { s: ["ALL"] },
    "template.group_manage": { s: ["NH"] },
    "media.use": { s: ["ALL"] },
    "channel.status": { s: ["NICK"] },
    "friend.respond": { s: ["NICK"] },
    "group.manage": { s: ["NICK"] },
    "channel.safety_confirm": { s: ["NICK"] },
    "grant.request": { s: ["ALL"] },
    "grant.leave_request": { s: ["ALL"] },
    "grant.delegate": { s: ["NH"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["SELF"] },
  },
  quan_sat: {
    "conv.view": { s: ["TD"], log: true },
    "conv.view_unassigned": { s: ["TD"] },
    "msg.attachment": { s: ["TD"], log: true },
    "search.global": { s: ["TD"], log: true },
    "cust.view": { s: ["TD"] },
    "cust.timeline": { s: ["TD"], log: true },
    "cust.commerce": { s: ["TD"] },
    "cust.debt": { s: ["TD"] },
    "cust.ai_summary": { s: ["TD"] },
    "cust.phone_full": { s: [], log: true, reveal: ["TD"] },
    "cust.commitments": { s: ["TD"] },
    "export.approve": { s: ["TD"] },
    "cust.privacy_request": { s: ["TD"], mode: "view" },
    "erp.lookup": { s: ["ALL"] },
    "quote.view": { s: ["TD"] },
    "invoice.view": { s: ["TD"] },
    "debt.note": { s: ["TD"], mode: "view" },
    "ticket.view": { s: ["TD"] },
    "media.use": { s: ["ALL"] },
    "campaign.report": { s: ["TD"] },
    "cost.view": { s: ["TD"] },
    "ads.manage": { s: ["TD"] },
    "lead.view": { s: ["TD"] },
    "lead.card": { s: ["TD"] },
    "channel.status": { s: ["TD"] },
    "sync.view": { s: ["TD"] },
    "org.view": { s: ["TD"] },
    "user.view": { s: ["TD"] },
    "role.approve": { s: ["ALL"] },
    "permission.explain": { s: ["TD"] },
    "access.review": { s: ["TD"], mode: "view" },
    "role.view": { s: ["ALL"] },
    "token.own": { s: ["ALL"] },
    "audit.view": { s: ["TD"] },
    "alert.handle": { s: ["TD"] },
    "alert.config": { s: ["ALL"], mode: "propose" },
    "config.sla": { s: ["ALL"], mode: "view" },
    "config.report_target": { s: ["TD"], mode: "propose" },
    "config.retention": { s: ["ALL"] },
    "config.security": { s: ["ALL"], mode: "view" },
    "report.volume": { s: ["TD"] },
    "report.performance": { s: ["TD"] },
    "report.source": { s: ["TD"] },
    "report.care": { s: ["TD"] },
    "report.data_quality": { s: ["TD"] },
    "report.ticket": { s: ["TD"] },
    "report.invoice": { s: ["TD"] },
    "report.export": { s: ["TD"], log: true },
    "report.snapshot_accept": { s: ["TD"] },
  },
};
// </generated:permissions>

/** One ✔/✖ line of the "Quyền hiệu lực" tab (MH-PQ-03, L-01). */
export interface EffectiveCheck {
  key: PermissionKey;
  label: string;
  allowed: boolean;
  /** Vietnamese reason: why it is allowed or what is missing. */
  reason: string;
}

export interface EffectiveTargetResult {
  /** Conversation id `${uid}:${threadId}`; the display name is abbreviated and no content or phone is returned. */
  conversationId: string;
  label: string;
  channelLabel: string | null;
  checks: EffectiveCheck[];
  /** When the answer is ✖ for viewing: who owns the customer and who approves a temporary grant. */
  howToSee: string | null;
  /** "Tạo yêu cầu quyền hộ" is offered: viewing is refused and somebody can approve (L-01 phần 2, PQ-70). */
  canRequestGrant?: boolean;
  /** Who would approve a temporary grant for this person on this target. */
  approverName?: string | null;
}

/** `GET /api/admin/users/:id/effective?target=` (permission.explain, logged without any content). */
export interface EffectiveRightsResponse {
  userId: string;
  fullName: string;
  results: EffectiveTargetResult[];
  /** The text was too short or matched nothing. */
  note: string | null;
}
