// TK-16 SCR-16.2: form thật, tạo môn giữ nội dung, xem trước thẻ, đa phương tiện, cây và màn nhỏ.
import { test, expect, seedOrg, pageAs, uid, mongo } from './fixtures'
import AxeBuilder from '@axe-core/playwright'

const ok = async r => { expect(r.ok(), await r.text()).toBeTruthy(); return r.json() }
test('soạn bài giữ nội dung khi tạo môn, tạo câu hỏi ngay, xem trước thẻ và học liệu không bắt buộc thẻ', async ({ page, browser }) => {
  test.setTimeout(120_000)
  const { people } = await seedOrg(page)
  const tp = await pageAs(browser, people.tp_part_kd)
  const s = uid()
  const space = await ok(await tp.request.post('/api/spaces', { data: { name: 'Kho đào tạo ' + s } }))
  await ok(await tp.request.post(`/api/spaces/${space.id}/members`, { data: { email: people.nv_part_kd.email, role: 'viewer' } }))
  const faculty = await ok(await tp.request.post('/api/learn/structure', { data: { kind: 'faculty', title: 'Khoa Kế hoạch ' + s, space_id: space.id } }))
  const department = await ok(await tp.request.post('/api/learn/structure', { data: { kind: 'department', title: 'Bộ môn VCS ' + s, parent_id: faculty.id, space_id: space.id } }))
  const card = await ok(await tp.request.post('/api/wiki/cards', { data: { space_id: space.id, type: 'concept', title: 'Dữ liệu VCS ' + s, summary: 'Phân tích công suất', body: 'Đọc số liệu hoạt động của xưởng VCS.' } }))
  mongo(`db.wiki_cards.updateOne({_id:ObjectId('${card.id}')},{$set:{status:'approved'}})`)
  await tp.goto('/learn/lessons/new')
  await tp.getByLabel('Tên bài học', { exact: true }).fill('Kế hoạch kinh doanh 2027 cho xưởng VCS ' + s)
  await tp.getByLabel('Diễn giải', { exact: true }).fill('Bản soạn cần giữ nguyên khi tạo môn.')
  await tp.getByLabel('Lưu vào kho', { exact: true }).selectOption(space.id)
  await tp.getByTestId('lesson-create-subject').click()
  const node = tp.getByTestId('training-node-form')
  await node.getByLabel('Tên Môn học').fill('Kế hoạch VCS ' + s)
  await node.getByLabel('Bộ môn phụ trách').selectOption(department.id)
  await node.getByRole('button', { name: 'Lưu Môn học', exact: true }).click()
  await expect(node).toHaveCount(0)
  await expect(tp.getByLabel('Tên bài học', { exact: true })).toHaveValue('Kế hoạch kinh doanh 2027 cho xưởng VCS ' + s)
  await expect(tp.getByLabel('Diễn giải', { exact: true })).toHaveValue('Bản soạn cần giữ nguyên khi tạo môn.')
  await tp.getByTestId('lesson-card-search').fill(card.id)
  await tp.getByRole('button', { name: 'Xem trước thẻ: Dữ liệu VCS ' + s }).click()
  await expect(tp.getByTestId('lesson-card-preview')).toContainText('Đọc số liệu hoạt động')
  await tp.keyboard.press('Escape')
  await tp.getByTestId('lesson-create-question').click()
  await tp.getByLabel('Đề bài', { exact: true }).fill('Dữ liệu đầu vào của kế hoạch VCS ' + s)
  await tp.getByLabel('Phương án 1', { exact: true }).fill('Số liệu 2026')
  await tp.getByLabel('Phương án 2', { exact: true }).fill('Đoán không có nguồn')
  await tp.getByLabel('Gắn thẻ căn cứ', { exact: true }).fill(card.id)
  await tp.getByTestId('q-form').getByRole('button', { name: '+ Dữ liệu VCS ' + s }).click()
  await tp.getByTestId('q-save-draft').click()
  await expect(tp.getByTestId('q-form')).toHaveCount(0)
  await expect(tp.getByLabel('Diễn giải', { exact: true })).toHaveValue('Bản soạn cần giữ nguyên khi tạo môn.')
  await expect(tp.getByTestId('lesson-practice')).toContainText('Dữ liệu đầu vào của kế hoạch VCS ' + s)
  await tp.getByTestId('lesson-practice').getByRole('checkbox').uncheck()
  await tp.getByRole('button', { name: '+ Học liệu', exact: true }).click()
  await tp.getByLabel('Tên học liệu 1').fill('Bản trình chiếu VCS')
  await tp.getByLabel('Loại học liệu', { exact: true }).selectOption('slides')
  await tp.getByLabel('Liên kết học liệu', { exact: true }).fill('https://example.com/vcs.pdf')
  await tp.getByTestId('lesson-publish').click()
  await tp.getByRole('button', { name: 'Xác nhận phát hành', exact: true }).click()
  await expect(tp.getByTestId('lesson-status')).toHaveText('Đã phát hành')
  await expect(tp.getByTestId('material-1')).toContainText('Bản trình chiếu VCS')
  const lessonUrl = tp.url()
  const nv = await pageAs(browser, people.nv_part_kd)
  await nv.goto(lessonUrl)
  await expect(nv.getByTestId('material-1')).toContainText('Bắt buộc')
  await nv.setViewportSize({ width: 375, height: 812 })
  await expect(nv.getByRole('link', { name: 'Mở / tải trình chiếu' })).toBeVisible()
  expect(await nv.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  const a11y = await new AxeBuilder({ page: nv }).analyze()
  expect(a11y.violations.filter(x => ['critical', 'serious'].includes(x.impact))).toEqual([])
  await tp.goto('/learn/library?tab=subjects')
  await tp.getByRole('button', { name: 'Kế hoạch VCS ' + s, exact: true }).click()
  await expect(tp.getByTestId('training-tree')).toContainText('Kế hoạch kinh doanh 2027 cho xưởng VCS ' + s)
  const reviewer = await pageAs(browser, people.tgd)
  await ok(await tp.request.post(`/api/spaces/${space.id}/members`, { data: { email: people.tgd.email, role: 'editor' } }))
  await tp.getByRole('tab', { name: 'Giáo trình', exact: true }).click()
  await tp.getByTestId('training-curriculum-new').click()
  const form = tp.getByTestId('training-document-form')
  await form.getByLabel('Tên tài liệu', { exact: true }).fill('Giáo trình VCS ' + s)
  await form.getByLabel('Lưu vào kho', { exact: true }).selectOption(space.id)
  await form.getByRole('button', { name: '+ Kế hoạch kinh doanh 2027 cho xưởng VCS ' + s, exact: true }).click()
  await form.getByRole('button', { name: 'Lưu nháp', exact: true }).click()
  await expect(form).toHaveCount(0)
  const curriculum = (await ok(await tp.request.get('/api/learn/documents?kind=curriculum'))).items.find(x => x.title === 'Giáo trình VCS ' + s)
  await reviewer.goto('/learn/library?tab=subjects&subject=' + curriculum.subject_id + '&section=curriculum')
  await reviewer.getByRole('button', { name: curriculum.title, exact: true }).click()
  await reviewer.getByRole('button', { name: 'Duyệt tài liệu', exact: true }).click()
  await expect(reviewer.getByTestId('training-document-form')).toHaveCount(0)
  await tp.reload()
  await tp.getByRole('button', { name: curriculum.title, exact: true }).click()
  await tp.getByRole('button', { name: 'Phát hành', exact: true }).click()
  await expect(form).toHaveCount(0)
  await tp.getByRole('tab', { name: 'Giáo án', exact: true }).click()
  await tp.getByTestId('training-plan-new').click()
  await form.getByLabel('Tên tài liệu', { exact: true }).fill('Giáo án VCS ' + s)
  await form.getByLabel('Lưu vào kho', { exact: true }).selectOption(space.id)
  await form.getByLabel('Giáo trình', { exact: true }).selectOption(curriculum.id)
  for (let i = 0; i < 2; i++) {
    await form.getByRole('button', { name: '+ Thêm buổi', exact: true }).click()
    const session = form.locator('section').filter({ has: tp.getByRole('heading', { name: 'Buổi ' + (i + 1), exact: true }) })
    await session.getByLabel('Tên buổi', { exact: true }).fill('Thực hành kế hoạch ' + (i + 1))
    await session.getByRole('button', { name: '+ Kế hoạch kinh doanh 2027 cho xưởng VCS ' + s, exact: true }).click()
  }
  await form.getByRole('button', { name: 'Lưu nháp', exact: true }).click()
  await expect(form).toHaveCount(0)
  const plan = (await ok(await tp.request.get('/api/learn/documents?kind=plan'))).items.find(x => x.title === 'Giáo án VCS ' + s)
  expect(plan.sessions).toHaveLength(2)
  expect(plan.sessions[0].lesson_ids).toEqual(plan.sessions[1].lesson_ids)
  await tp.goto(lessonUrl)
  await tp.getByTestId('lesson-copy').click()
  await tp.getByLabel('Tên bài học', { exact: true }).fill('Kế hoạch VCS bản bổ sung ' + s)
  const copiedId = tp.url().split('/lessons/')[1].split('/')[0]
  await tp.getByTestId('lesson-save-draft').click()
  await expect(tp).toHaveURL(/\/learn\/library/)
  await tp.goto('/learn/lessons/' + copiedId)
  await expect(tp.getByTestId('lesson-status')).toHaveText('Nháp')
  await expect(tp.getByRole('heading', { name: 'Kế hoạch VCS bản bổ sung ' + s, exact: true })).toBeVisible()
  await nv.goto(lessonUrl)
  await expect(nv.getByRole('heading', { name: 'Kế hoạch kinh doanh 2027 cho xưởng VCS ' + s, exact: true })).toBeVisible()
  await reviewer.context().close()
  await tp.context().close(); await nv.context().close()
})

test('người học nộp dự án SEO và người được phân công chấm bằng rubric', async ({ page, browser }) => {
  test.setTimeout(60_000)
  const { people } = await seedOrg(page)
  const author = await pageAs(browser, people.tp_part_kd)
  const reviewer = await pageAs(browser, people.tgd)
  const learner = await pageAs(browser, people.nv_part_kd)
  const s = uid()
  const space = await ok(await author.request.post('/api/spaces', { data: { name: 'Thực hành ' + s } }))
  for (const [person, role] of [[people.tgd, 'editor'], [people.nv_part_kd, 'viewer']]) {
    await ok(await author.request.post(`/api/spaces/${space.id}/members`, { data: { email: person.email, role } }))
  }
  const node = async (kind, title, parent_id) => ok(await author.request.post('/api/learn/structure', { data: { kind, title, parent_id, space_id: space.id } }))
  const faculty = await node('faculty', 'Marketing ' + s)
  const department = await node('department', 'SEO ' + s, faculty.id)
  const subject = await node('subject', 'Kế hoạch SEO ' + s, department.id)
  let task = await ok(await author.request.post('/api/learn/tasks', { data: { title: 'Kế hoạch SEO website X ' + s, kind: 'project', subject_id: subject.id, space_id: space.id, mission: 'Xây dựng kế hoạch SEO website X', inputs: 'Dữ liệu tìm kiếm website X', deliverable: 'Kế hoạch SEO', rubric: [{ title: 'Mục tiêu và đo lường', weight: 100 }] } }))
  task = await ok(await reviewer.request.post(`/api/learn/tasks/${task.id}/approve?revision=${task.revision}`))
  task = await ok(await author.request.post(`/api/learn/tasks/${task.id}/publish?revision=${task.revision}`))
  await ok(await author.request.post(`/api/learn/tasks/${task.id}/assign`, { data: { learner_ids: [people.nv_part_kd.id], mentor_id: people.tp_part_kd.id, grader_id: people.tp_part_kd.id, due_at: new Date(Date.now() + 86400000).toISOString() } }))
  await learner.goto('/learn/library?tab=work')
  await learner.getByTestId('work-open').click()
  await learner.getByTestId('work-product').fill('Mục tiêu tăng truy cập hữu ích, đo bằng kết quả tìm kiếm và chuyển đổi; kế hoạch nội dung theo nhóm nhu cầu.')
  await learner.getByRole('button', { name: 'Nộp thực hành', exact: true }).click()
  await expect(learner.getByTestId('work-form')).toHaveCount(0)
  await expect(learner.getByText('Chờ chấm', { exact: false })).toBeVisible()
  await author.goto('/learn/library?tab=work')
  await author.getByTestId('work-open').click()
  await author.getByLabel('Điểm Mục tiêu và đo lường (0…100)', { exact: true }).fill('85')
  await author.getByLabel('Nhận xét bắt buộc', { exact: true }).fill('Mục tiêu phù hợp, cần bổ sung lịch đo hàng tháng.')
  await author.getByRole('button', { name: 'Chốt điểm thực hành', exact: true }).click()
  await expect(author.getByTestId('work-form')).toHaveCount(0)
  await learner.reload()
  await expect(learner.getByText('Đã đạt', { exact: false })).toBeVisible()
  await learner.getByTestId('work-open').click()
  await expect(learner.getByTestId('work-form')).toContainText('85%')
  await expect(learner.getByRole('button', { name: 'Nộp thực hành', exact: true })).toHaveCount(0)
  await author.context().close(); await reviewer.context().close(); await learner.context().close()
})
